#!/bin/bash
cd "${0%/*}"
mkdir -p "/home/$USER"
mkdir -p "/home/$USER/bin"
mkdir -p "/home/$USER/.config/autorandr/docked"
mkdir -p "/home/$USER/.config/autorandr/home"
mkdir -p "/home/$USER/.config/autorandr/mobile"
mkdir -p "/home/$USER/.config/cava"
mkdir -p "/home/$USER/.config/Dharkael"
mkdir -p "/home/$USER/.config/dunst"
mkdir -p "/home/$USER/.config/i3"
mkdir -p "/home/$USER/.config/nvim"
mkdir -p "/home/$USER/.config/polybar"
mkdir -p "/home/$USER/.config/ranger"
mkdir -p "/home/$USER/dotfiles"
ln -sf ".bash_aliases" "/home/$USER/.bash_aliases"
ln -sf ".bash_profile" "/home/$USER/.bash_profile"
ln -sf ".bashrc" "/home/$USER/.bashrc"
ln -sf "bin/battery" "/home/$USER/bin/battery"
ln -sf "bin/cava-colors" "/home/$USER/bin/cava-colors"
ln -sf "bin/color" "/home/$USER/bin/color"
ln -sf "bin/dotify" "/home/$USER/bin/dotify"
ln -sf "bin/i3-get-window-criteria" "/home/$USER/bin/i3-get-window-criteria"
ln -sf "bin/location" "/home/$USER/bin/location"
ln -sf "bin/monitor" "/home/$USER/bin/monitor"
ln -sf "bin/set_title" "/home/$USER/bin/set_title"
ln -sf "bin/term-launch" "/home/$USER/bin/term-launch"
ln -sf "bin/theme" "/home/$USER/bin/theme"
ln -sf "bin/volume" "/home/$USER/bin/volume"
ln -sf "bin/wal-edit" "/home/$USER/bin/wal-edit"
ln -sf "bin/weather" "/home/$USER/bin/weather"
ln -sf "bin/weather_widget" "/home/$USER/bin/weather_widget"
ln -sf ".config/autorandr/docked/config" "/home/$USER/.config/autorandr/docked/config"
ln -sf ".config/autorandr/docked/postswitch" "/home/$USER/.config/autorandr/docked/postswitch"
ln -sf ".config/autorandr/home/config" "/home/$USER/.config/autorandr/home/config"
ln -sf ".config/autorandr/mobile/config" "/home/$USER/.config/autorandr/mobile/config"
ln -sf ".config/autorandr/mobile/postswitch" "/home/$USER/.config/autorandr/mobile/postswitch"
ln -sf ".config/cava/config" "/home/$USER/.config/cava/config"
ln -sf ".config/Dharkael/flameshot.ini" "/home/$USER/.config/Dharkael/flameshot.ini"
ln -sf ".config/dunst/dunstrc" "/home/$USER/.config/dunst/dunstrc"
ln -sf ".config/i3/config" "/home/$USER/.config/i3/config"
ln -sf ".config/nvim/init.vim" "/home/$USER/.config/nvim/init.vim"
ln -sf ".config/polybar/config" "/home/$USER/.config/polybar/config"
ln -sf ".config/polybar/launch.sh" "/home/$USER/.config/polybar/launch.sh"
ln -sf ".config/ranger/rc.conf" "/home/$USER/.config/ranger/rc.conf"
ln -sf ".config/ranger/rifle.conf" "/home/$USER/.config/ranger/rifle.conf"
ln -sf "dotfiles/fancyconfig" "/home/$USER/dotfiles/fancyconfig"
ln -sf "fancyconfig" "/home/$USER/fancyconfig"
ln -sf ".gitconfig" "/home/$USER/.gitconfig"
ln -sf ".profile" "/home/$USER/.profile"
ln -sf ".zshrc" "/home/$USER/.zshrc"
