#!/bin/bash
cd "${0%/*}"
mkdir -p "/home/$USER"
mkdir -p "/home/$USER/bin"
mkdir -p "/home/$USER/.config/autorandr/docked"
mkdir -p "/home/$USER/.config/autorandr/home"
mkdir -p "/home/$USER/.config/autorandr/mobile"
mkdir -p "/home/$USER/.config/cava"
mkdir -p "/home/$USER/.config/Dharkael"
mkdir -p "/home/$USER/.config/dunst"
mkdir -p "/home/$USER/.config/i3"
mkdir -p "/home/$USER/.config/nvim"
mkdir -p "/home/$USER/.config/polybar"
mkdir -p "/home/$USER/.config/ranger"
mkdir -p "/home/$USER/dotfiles"
mkdir -p "/home/$USER/themes"
mkdir -p "/home/$USER/themes/override"
ln -sfr ".bash_aliases" "/home/$USER/.bash_aliases"
ln -sfr ".bash_profile" "/home/$USER/.bash_profile"
ln -sfr ".bashrc" "/home/$USER/.bashrc"
ln -sfr "bin/battery" "/home/$USER/bin/battery"
ln -sfr "bin/cava-colors" "/home/$USER/bin/cava-colors"
ln -sfr "bin/color" "/home/$USER/bin/color"
ln -sfr "bin/dotify" "/home/$USER/bin/dotify"
ln -sfr "bin/i3-get-window-criteria" "/home/$USER/bin/i3-get-window-criteria"
ln -sfr "bin/location" "/home/$USER/bin/location"
ln -sfr "bin/monitor" "/home/$USER/bin/monitor"
ln -sfr "bin/set_title" "/home/$USER/bin/set_title"
ln -sfr "bin/term-launch" "/home/$USER/bin/term-launch"
ln -sfr "bin/theme" "/home/$USER/bin/theme"
ln -sfr "bin/volume" "/home/$USER/bin/volume"
ln -sfr "bin/wal-edit" "/home/$USER/bin/wal-edit"
ln -sfr "bin/weather" "/home/$USER/bin/weather"
ln -sfr "bin/weather_widget" "/home/$USER/bin/weather_widget"
ln -sfr ".config/autorandr/docked/config" "/home/$USER/.config/autorandr/docked/config"
ln -sfr ".config/autorandr/docked/postswitch" "/home/$USER/.config/autorandr/docked/postswitch"
ln -sfr ".config/autorandr/home/config" "/home/$USER/.config/autorandr/home/config"
ln -sfr ".config/autorandr/mobile/config" "/home/$USER/.config/autorandr/mobile/config"
ln -sfr ".config/autorandr/mobile/postswitch" "/home/$USER/.config/autorandr/mobile/postswitch"
ln -sfr ".config/cava/config" "/home/$USER/.config/cava/config"
ln -sfr ".config/Dharkael/flameshot.ini" "/home/$USER/.config/Dharkael/flameshot.ini"
ln -sfr ".config/dunst/dunstrc" "/home/$USER/.config/dunst/dunstrc"
ln -sfr ".config/i3/config" "/home/$USER/.config/i3/config"
ln -sfr ".config/nvim/init.vim" "/home/$USER/.config/nvim/init.vim"
ln -sfr ".config/polybar/config" "/home/$USER/.config/polybar/config"
ln -sfr ".config/polybar/launch.sh" "/home/$USER/.config/polybar/launch.sh"
ln -sfr ".config/ranger/rc.conf" "/home/$USER/.config/ranger/rc.conf"
ln -sfr ".config/ranger/rifle.conf" "/home/$USER/.config/ranger/rifle.conf"
ln -sfr ".gitconfig" "/home/$USER/.gitconfig"
ln -sfr ".profile" "/home/$USER/.profile"
ln -sfr "themes/override/monokai" "/home/$USER/themes/override/monokai"
ln -sfr "themes/override/vscode" "/home/$USER/themes/override/vscode"
ln -sfr "themes/portal.json" "/home/$USER/themes/portal.json"
ln -sfr ".zshrc" "/home/$USER/.zshrc"
