[[task]]
  id = "stream"
  type = "long"
  dependencies = ["chat", "tau", "bus"]

[[task]]
  id = "tau"
  type = "long"
  cmd = "tau-websocket"
  watch = ["bin/twitch-cmds/tau-websocket"]

[[task]]
  id = "chat"
  type = "long"
  cmd = "twitch-chat badcop_"
  watch = ["bin/twitch-cmds/twitch-chat", "bin/twitch-cmds/fish-cmds", "bin/twitch-cmds/jam-cmds", "bin/twitch-cmds/ld-cmds"]

[[task]]
  id = "bus"
  type = "long"
  cmd = "tau-message-broker"
  watch = ["bin/twitch-cmds/tau-message-broker"]
