#!/bin/bash

sleep 5

killall compton
sleep 2
xrandr --output HDMI-1 --primary

i3-msg -t get_workspaces | jq -r '.[].num' | \
while read -r workspace; do
    # Don't move slack / spotify
    if [[ "$workspace" == "5" || "$workspace" == "10" ]]; then
        continue
    fi
    echo "moving ${workspace} right..."
    i3-msg workspace "${workspace}"
    i3-msg move workspace to output HDMI-1
done

# Switch to slack
i3-msg workspace 5

sleep 3

i3-msg reload

