endpoint: https://samsaradev.atlassian.net
editor: vim
accountId: 5c6b1a0acf74864794a31cb5
login: sarah.schulte@samsara.com

custom-commands:
  - name: mysprint
    help: display issues assigned to me in SRE
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('In Review', 'Review', 'Merged', 'Archive') and assignee=currentuser() AND project IN ('RE')"

  - name: mysprint_old
    help: display issues assigned to me in my current sprint
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('In Review', 'Review', 'Merged', 'Archive') and assignee=currentuser() and sprint in openSprints() ORDER BY priority,created"

  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('In Review', 'Review', 'Merged', 'Archive') and assignee=currentuser() ORDER BY priority,created"

  - name: current-sprint
    help: gets the currently active sprint ID
    args:
      - name: PROJECT
        required: true
    script: |
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId={{args.PROJECT}}" --gjq values | jq -c '.[] | select(.location.projectKey == "MOB").id')

      {{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0.id

  - name: take2
    help: self-assigns the specified ticket
    args:
      - name: TICKET
        required: true
    script: |
      {{jira}} req -v -t empty -M PUT "/rest/api/3/issue/{{args.TICKET}}/assignee" "{\"accountId\": \"5c6b1a0acf74864794a31cb5\" }" 2> /dev/null > /dev/null || exit 0
